#ifndef __REMOTE_PORT_H__
    #define __REMOTE_PORT_H__

    typedef enum{
        REMOTE_PROPERTY_START,
        REMOTE_PROPERTY_GENERAL=0x01,
        REMOTE_PROPERTY_CONTROL=0x02,
        REMOTE_PROPERTY_SYSTEMSETTINGS=0x04,
        REMOTE_PROPERTY_WORKOUTTRACKING=0x08,
        REMOTE_PROPERTY_ASSET=0x10,
        REMOTE_PROPERTY_USER=0x20,
        REMOTE_PROPERTY_END
    }RemoteProperty;

typedef enum
{
    GENERAL_COMMAND_START,
	GENERAL_ACKNOWLEDGMENT = GENERAL_COMMAND_START,
	GENERAL_GET_LING_VERSION,
	GENERAL_GET_MACHINE_INFO,
	GENERAL_SET_SPEED_CALIBRATION,
	GENERAL_GET_SPEED_CALIBRATION,
	GENERAL_SET_PWM_CAL,//5
	
	GENERAL_GET_PWM_CAL,
	GENERAL_SET_ECB_CAL,
	GENERAL_GET_ECB_CAL,
	GENERAL_SET_WATTS_TABLE,
	GENERAL_GET_WATTS_TABLE,//10
	
	GENERAL_SET_DATA_SERVER,
	GENERAL_GET_DATA_SERVER,
	GENERAL_SET_MACHINE_STATE,
	GENERAL_GET_MACHINE_STATE,
	GENERAL_SET_USER_DATA,//15
	
	GENERAL_GET_USER_DATA,
	GENERAL_SET_WORKOUT_DATA_RATE,
	GENERAL_GET_WORKOUT_DATA,
	GENERAL_GET_CURRENT_USER,
	GENERAL_STOP_WORKOUT,//20
	
	GENERAL_CHECK_FOR_UPDATE,
    GENERAL_SYNC_USER_DATA,
    GENERAL_SET_MY_FIRST_5K,
    GENERAL_SET_CUSTOM_PROGRAM,
    GENERAL_SET_CUSTOM_HR_PROGRAM,//25
    
    GENERAL_PUSH_WORKOUT_SUMMARY,
    GENERAL_SET_POPUP_INFORMATION,   
	GENERAL_COMMAND_END
} RemoteGeneralCommand;//0x02

typedef enum
{
    CONTROL_REMOTE_START,
	CONTROL_REMOTE_ACKNOWLEDGMENT = CONTROL_REMOTE_START,
	CONTROL_SET_CURRENT_USER,
	CONTROL_START,
	CONTROL_PAUSE,
//	CONTROL_RESTART,
	CONTROL_CHANGE_PROGRAM,//5
	
	CONTROL_SET_SPEED,
	CONTROL_SET_INCLINE,
	CONTROL_SET_RESISTANCE,
	CONTROL_SET_RAW_ECB,
	CONTROL_SET_RAW_PWM, //5
	
	CONTROL_SELECT_PROGRAM,
	CONTROL_KEY_PRESS,
    CONTROL_DELETE_USER,
    CONTROL_GET_HEARTRATE=0X13,
    CONTROL_GET_NETWORK_TIME,
	CONTROL_REMOTE_END
} RemoteControlCommand;

typedef enum
{
       SYSTEM_SETTINGS_START,
	SYSTEM_SETTINGS_ACKNOWLEDGMENT = SYSTEM_SETTINGS_START,
	SYSTEM_SET_DEFAULTS,
	SYSTEM_GET_DEFAULTS,

	SYSTEM_SET_MACHINE_TYPE,
	SYSTEM_GET_MACHINE_TYPE,

	SYSTEM_SET_REGION,
	SYSTEM_GET_REGION,
	
	SYSTEM_SETTINGS_END
} RemoteSystemCommand;

typedef enum
{
       REMOTE_WORKOUT_TRACKING_START,
	REMOTE_WORKOUT_TRACKING_ACKNOWLEDGMENT = REMOTE_WORKOUT_TRACKING_START,//0
	REMOTE_WORKOUT_TRACKING_START_WORKOUT,//1
	REMOTE_WORKOUT_TRACKING_WORKOUT_DATA,//2
	REMOTE_WORKOUT_TRACKING_WORKOUT_COMPLETE,//3
	REMOTE_WORKOUT_TRACKING_GET_WORKOUTS,//4
	REMOTE_WORKOUT_TRACKING_GET_WORKOUT,
	REMOTE_WORKOUT_TRACKING_DATA_EX = 0x06,
	REMOTE_WORKOUT_TRACKING_COMPLETE_EX= 0x07,
	REMOTE_WORKOUT_TRACKING_SPRINT8_COMPLETE_EXTRA = 0x08,
	REMOTE_WORKOUT_TRACKING_FITNESS_COMPLETE_EXTRA = 0x09,
	REMOTE_WORKOUT_TRACKING_END
} RemoteWorkoutTrackingCommand;//0x80

typedef enum
{
       REMOTE_ASSET_MANAGEMENT_START,
	REMOTE_ASSET_MANAGEMENT_ACKNOWLEDGMENT =REMOTE_ASSET_MANAGEMENT_START,//0
	REMOTE_ASSET_MANAGEMENT_MACHINE_INFO,
	REMOTE_ASSET_MANAGEMENT_MACHINE_REGISTRATION,
	REMOTE_ASSET_MANAGEMENT_GET_DAPI_LOCATION,
	REMOTE_ASSET_MANAGEMENT_CONSOLE_SKIN,
	REMOTE_ASSET_MANAGEMENT_GET_LATEST_VERSION,
	REMOTE_ASSET_MANAGEMENT_I_DONT_KNOW,
	REMOTE_ASSET_MANAGEMENT_MACHINE_INFO_EX ,
	REMOTE_ASSET_MANAGEMENT_UPDATE_MACHINE_STATE ,
	REMOTE_ASSET_MANAGEMENT_ERROR_CODE_OCCURRED ,
	REMOTE_ASSET_MANAGEMENT_SERVICE_CODE_OCCURRED ,
	REMOTE_ASSET_MANAGEMENT_GET_CONSOLE_CONFIG_URL ,
	REMOTE_ASSET_MANAGEMENT_GET_MESSAGE_CENTER_URL ,
	REMOTE_ASSET_MANAGEMENT_GET_NETWORK_TIME,
	REMOTE_ASSET_MANAGEMENT_END
} RemoteAssetManagementCommand;//0x81

typedef enum
{
       REMOTE_USER_START,
	REMOTE_USER_MANAGEMENT_ACKNOWLEDGMENT = REMOTE_USER_START,//0
	REMOTE_SYNC_USER_INFO,//1
	REMOTE_USER_LOGIN,//2
	REMOTE_USER_REGISTRATION,//3
	REMOTE_USER_CHECK_XID,//4
	REMOTE_USER_CLEAR_USERS,//5
	REMOTE_USER_RESET_PASSWORD,//6
	REMOTE_USER_SET_KEY_STORE,//7
	REMOTE_USER_GET_KEY_STORE,//8
	REMOTE_USER_GET_CALORIE_INFO,//9 
	REMOTE_USER_UNLINK_USER,//0x0a
	REMOTE_USER_GET_SOCAIL_MEDIA_CONNECTED=0x0e,
	REMOTE_USER_SEND_SOCAIL_MEDIA = 0x0F,
	REMOTE_USER_CHECK_UNIQUE_EMAIL=0x10,
	REMOTE_USER_HAS_PERSONAL_TRAINER = 0x11,
	REMOTE_USER_RFID_LOGIN = 0x12,
	REMOTE_USER_RFID_ASSOCIATE = 0x13,
	REMOTE_USER_RFID_DISASSOCIATE =0x14,
	REMOTE_USER_GET_NUMBER_LEADER_BOARDS = 0x15,
	REMOTE_USER_END
} RemoteUserCommand;//0x83


    
typedef enum{
    REMOTE_COMMAND_START,
        
    REMOTE_COMMAND_GENERAL_START = (REMOTE_PROPERTY_GENERAL<<8)|GENERAL_COMMAND_START,
    RCMD_GENERAL_ACKNOWLEDGMENT = REMOTE_COMMAND_GENERAL_START,
    RCMD_GENERAL_GET_LING_VERSION,
    RCMD_GENERAL_GET_MACHINE_INFO,
    RCMD_GENERAL_SET_SPEED_CALIBRATION,
    RCMD_GENERAL_GET_SPEED_CALIBRATION,
    RCMD_GENERAL_SET_PWM_CAL, //5    
    RCMD_GENERAL_GET_PWM_CAL,
    RCMD_GENERAL_SET_ECB_CAL,
    RCMD_GENERAL_GET_ECB_CAL,
    RCMD_GENERAL_SET_WATTS_TABLE,
    RCMD_GENERAL_GET_WATTS_TABLE, //10    
    RCMD_GENERAL_SET_DATA_SERVER,
    RCMD_GENERAL_GET_DATA_SERVER,
    RCMD_GENERAL_SET_MACHINE_STATE,
    RCMD_GENERAL_GET_MACHINE_STATE,
    RCMD_GENERAL_SET_USER_DATA, // 15    
    RCMD_GENERAL_GET_USER_DATA,
    RCMD_GENERAL_SET_WORKOUT_DATA_RATE,
    RCMD_GENERAL_GET_WORKOUT_DATA,
    RCMD_GENERAL_GET_CURRENT_USER,
    RCMD_GENERAL_STOP_WORKOUT, //20    
    RCMD_GENERAL_CHECK_FOR_UPDATE,
    RCMD_GENERAL_SYNC_USER_DATA,
    RCMD_GENERAL_SET_MY_FIRST_5K,
    RCMD_GENERAL_SET_CUSTOM_PROGRAM,
    RCMD_GENERAL_SET_CUSTOM_HR_PROGRAM,//25
    RCMD_GENERAL_PUSH_WORKOUT_SUMMARY,
    RCMD_GENERAL_POPUP_INFORMATION,
    REMOTE_COMMAND_GENERAL_END = (REMOTE_PROPERTY_GENERAL<<8)|GENERAL_COMMAND_END,
    
    REMOTE_COMMAND_CONTROL_START = (REMOTE_PROPERTY_CONTROL<<8)|CONTROL_REMOTE_START,
    RCMD_CONTROL_ACKNOWLEDGMENT = REMOTE_COMMAND_CONTROL_START,
    RCMD_CONTROL_SET_CURRENT_USER,
    RCMD_CONTROL_START,
    RCMD_CONTROL_PAUSE,
//    RCMD_CONTROL_RESTART,
    RCMD_CONTROL_CHANGE_PROGRAM, //5    
    RCMD_CONTROL_SET_SPEED,
    RCMD_CONTROL_SET_INCLINE,
    RCMD_CONTROL_SET_RESISTANCE,
    RCMD_CONTROL_SET_RAW_ECB,
    RCMD_CONTROL_SET_RAW_PWM, //10    
    RCMD_CONTROL_SELECT_PROGRAM,
    RCMD_CONTROL_KEY_PRESS,    
    REMOTE_COMMAND_CONTROL_END = (REMOTE_PROPERTY_CONTROL<<8)|CONTROL_REMOTE_END,

    REMOTE_COMMAND_SYSTEM_START = (REMOTE_PROPERTY_SYSTEMSETTINGS<<8)|SYSTEM_SETTINGS_START,
    REMOTE_COMMAND_SYSTEM_END = (REMOTE_PROPERTY_SYSTEMSETTINGS<<8)|SYSTEM_SETTINGS_END,

    REMOTE_COMMAND_WORKOUT_START = (REMOTE_PROPERTY_WORKOUTTRACKING<<8)|REMOTE_WORKOUT_TRACKING_START,
    RCMD_WORKOUT_TRACKING_ACKNOWLEDGMENT = REMOTE_COMMAND_WORKOUT_START,//0
    RCMD_WORKOUT_TRACKING_START_WORKOUT,
    RCMD_WORKOUT_TRACKING_WORKOUT_DATA,//2
    RCMD_WORKOUT_TRACKING_WORKOUT_COMPLETE,//3
    RCMD_WORKOUT_TRACKING_GET_WORKOUTS,//4
    RCMD_WORKOUT_TRACKING_GET_WORKOUT, //5    
    RCMD_WORKOUT_TRACKING_DATA_EX ,
    RCMD_WORKOUT_TRACKING_COMPLETE_EX,
    RCMD_WORKOUT_TRACKING_SPRINT8_COMPLETE_EXTRA,
    RCMD_WORKOUT_TRACKING_FITNESS_COMPLETE_EXTRA,    
    REMOTE_COMMAND_WORKOUT_END = (REMOTE_PROPERTY_WORKOUTTRACKING<<8)|REMOTE_WORKOUT_TRACKING_END,

    REMOTE_COMMAND_ASSET_START = (REMOTE_PROPERTY_ASSET<<8)|REMOTE_ASSET_MANAGEMENT_START,
    RCMD_ASSET_ACKNOWLEDGMENT =REMOTE_COMMAND_ASSET_START,//0
    RCMD_ASSET_MACHINE_INFO,
    RCMD_ASSET_MACHINE_REGISTRATION,
    RCMD_ASSET_GET_DAPI_LOCATION,
    RCMD_ASSET_CONSOLE_SKIN,
    RCMD_ASSET_GET_LATEST_VERSION,//5    
    RCMD_ASSET_I_DONT_KNOW,
    RCMD_ASSET_MACHINE_INFO_EX ,
    RCMD_ASSET_UPDATE_MACHINE_STATE,
    RCMD_ASSET_ERROR_CODE_OCCURRED ,
    RCMD_ASSET_SERVICE_CODE_OCCURRED , //10    
    RCMD_ASSET_GET_CONSOLE_CONFIG_URL ,
    RCMD_ASSET_GET_MESSAGE_CENTER_URL ,    

    RCMD_ASSET_GET_NETWORK_TIME,
    REMOTE_COMMAND_ASSET_END = (REMOTE_PROPERTY_ASSET<<8)|REMOTE_ASSET_MANAGEMENT_END,

    REMOTE_COMMAND_USER_START = (REMOTE_PROPERTY_USER<<8)|REMOTE_USER_START,
    RCMD_USER_ACKNOWLEDGMENT = REMOTE_COMMAND_USER_START,//0
    RCMD_SYNC_USER_INFO,
    RCMD_USER_LOGIN,
    RCMD_USER_REGISTRATION,//3
    RCMD_USER_CHECK_XID,//4
    RCMD_USER_CLEAR_USERS,//5    
    RCMD_USER_RESET_PASSWORD,//6
    RCMD_USER_SET_KEY_STORE,//7
    RCMD_USER_GET_KEY_STORE,//8
    RCMD_USER_GET_CALORIE_INFO,//9 
    RCMD_USER_UNLINK_USER,//10    
    RCMD_USER_DONT_KNOW1,
    RCMD_USER_DONT_KNOW2,
    RCMD_USER_DONT_KNOW3,
    RCMD_USER_GET_SOCAIL_MEDIA_CONNECTED,
    RCMD_USER_SEND_SOCAIL_MEDIA, //15    
    RCMD_USER_CHECK_UNIQUE_EMAIL,
    RCMD_USER_HAS_PERSONAL_TRAINER ,
    RCMD_USER_RFID_LOGIN ,
    RCMD_USER_RFID_ASSOCIATE ,
    RCMD_USER_RFID_DISASSOCIATE , //20    
    RCMD_USER_GET_NUMBER_LEADER_BOARDS ,    
    REMOTE_COMMAND_USER_END = (REMOTE_PROPERTY_USER<<8)|REMOTE_USER_END,

    REMOTE_COMMAND_WIFI_START,
    REMOTE_WIFI_INITIAL = REMOTE_COMMAND_WIFI_START,
    REMOTE_WIFI_GET_INFOR,
    REMOTE_WIFI_SET_MARIOBOX,
    REMOTE_WIFI_GET_SIGNAL,
    REMOTE_WIFI_GET_STATUS,
    REMOTE_WIFI_RESTORE_FACTORY,
    REMOTE_WIFI_CONNECT_HOTPOINT,
    REMOTE_WIFI_SET_UPDATE_URL,
    REMOTE_WIFI_GET_HTTP_DATA,
    REMOTE_COMMAND_WIFI_END,

    
    REMOTE_COMMAND_BT_START,
    REMOTE_COMMAND_BT_SWITCHMODE,
    REMOTE_COMMAND_BT_STARTSCANNING,
    REMOTE_COMMAND_BT_STOPSCANNING,
    REMOTE_COMMAND_BT_SETBLENAME,
    REMOTE_COMMAND_BT_SETAMPNAME,
    REMOTE_COMMAND_BT_GETBLENAME,
    REMOTE_COMMAND_BT_GETLOCALNAME,
    REMOTE_COMMAND_BT_GETUPDATEINFO,   //zsf
    REMOTE_COMMAND_BT_STOPADVERTISELE,   //zsf
    REMOTE_COMMAND_BT_SETDISCOVERYMODE,   //zsf
    REMOTE_COMMAND_BT_SETCONNECTMODE,   //zsf
    REMOTE_COMMAND_BT_UARTUPDATE,    //zsf
    REMOTE_COMMAND_BT_END,

    
    REMOTE_COMMAND_END
}RemoteCommand;

#endif
