#ifndef _STRINGS
#define _STRINGS
#include "JIStypes.h"

#define __LANGUAGE_FRENCH__
//#define __LANGUAGE_GERMAN__
//#define __LANGUAGE_DUTCH__
#define __LANGUAGE_SPANISH__
//#define __LANGUAGE_ITALIAN__
//#define __LANGUAGE_PORTUGUESE__
//#define __LANGUAGE_VIETNAMESE__

typedef enum{
STRINGIDSTART,
STR_INITIAL_ID =STRINGIDSTART ,
STR_HEARTRATEMETER_ID,
STR_PASSPORTREADY_ID,
STR_RFSYNC_ID,
STR_SELECTUSER_ID,
STR_UPDATE_USER_ID,
STR_TIMEZONE_ID,

STR_GUEST_ID,
STR_USER1_ID,//10
STR_USER2_ID,
STR_USER3_ID,
STR_USER4_ID,
STR_USER5_ID,

STR_CONNECT_ID,
//STR_SYNC_USER_ID,
STR_SELECTWEIGHT_ID,
STR_SELECTAGE_ID,
STR_SELECTGENDER_ID,
STR_FEMALE_ID,
STR_MALE_ID,
STR_SELECTTIME_ID,//20
STR_SELECTSPEED_ID,
STR_SELECTINCLINE_ID,
STR_SELECTRESISTANCE_ID,
STR_SELECTLEVEL_ID,
STR_CONSTWATTS_ID,
STR_CUSTOM1_ID,
STR_MANUAL_ID,
STR_INTERVALWATTS_ID,
STR_THRZONE_ID,
STR_THRPERCENT_ID,//30
STR_CUSTOM2_ID,
STR_SELECTINTERVALWATTS_ID,
STR_SELECTTARGETWATTS_ID,
STR_SELECTINTERVALWATTS2_ID,
STR_SELECTHEARTRATEPERCENT_ID,
STR_TARGETHEARTRATEPERCENT_ID,
STR_PRESSSTART_ID,
STR_DISPLAYTEST_ID,
STR_HARDWARE_ID,
STR_NOT_AVAILABLE_ID,//40
STR_SWITCHFUNCATION_ID,
STR_INFORMATION_ID,
STR_HARDWARE1_ID, //zsf
STR_METRIC_ID,
STR_STANDARD_ID,


STR_ENGLISH_ID,
STR_FRENCH_ID,
//STR_GERMAN_ID,
//STR_DUTCH_ID,
STR_SPANISH_ID,//80
//STR_ITALIAN_ID,
//STR_PORTUGUESE_ID,
//STR_VIETNAMESE_ID,


STR_ENERGYSAVEON_ID,
STR_ENERGYSAVEOFF_ID,
STR_TEST_ID,//50
STR_QUICK_ID,
STR_NORMAL_ID,
STR_NOCLEAR_ID,
STR_CLEAR_ID,
STR_PRESSSTARTBUTTON_ID,
STR_RPMOFF_ID,
STR_RPMON_ID,
STR_WORKOUTPAUSE_ID,
STR_ERRORNOHEARTRATE_ID,
STR_HEARTRATECONTORL_ID,//60
//STR_COOLDOWN_ID,
STR_WORKOUTFINISH_ID,
STR_INTERVALS_ID,
STR_GAME_ID,
STR_FATBURN_ID,
STR_WEIGHTLOSSPLUS_ID,
STR_ROLLING_ID,
STR_CADENCE_ID,
STR_RANDOM_ID,
STR_WIN_ID,//70
STR_FAIL_ID,
STR_FITNESS_ID,
STR_STRENGTHBUILD_ID,
STR_KEEPSPEED_ID,
STR_VERYPOOR_ID,
STR_POOR_ID,
STR_AVERAGE_ID,
STR_GOOD_ID,
STR_EXCELLENT_ID,

STR_BEGINWKOT_ID,
STR_RESUMEWKOT_ID,
STR_TIMEOUT_ID,
STR_VOL_ID,
STR_LEVEl_ID,
//#ifdef __WIFI_FUNC__
STR_XID_ID,
STR_PASSCOD_ID,
STR_ENTER_XID_ID,
STR_DELETE_ID,
STR_EDIT_ID,//90
STR_SETPROFORMANCE_ID,
STR_SETINTERVAL_ID,
STR_SETCUSTOM_ID,
STR_SETPROGRAM_ID,
STR_WIFITEST_ID,
STR_SETCAL_ID,
STR_SETDISTANCE_ID,
STR_SETSTEP_ID,
STR_MILES_ID,
STR_HALFMALSON_ID,//100
STR_ACTIVATED_ID,
STR_EDITAUSER_ID,
STR_DELETEUSER_ID,
STR_LOGIN_ID,
STR_WAIT_ID,
STR_WELCOME_ID,
STR_INVALIDPW_ID,
STR_SUCCESS_ID,
STR_OFFLINE_ID,
STR_SPINTERVAL_ID,//110
STR_ENDURANCE_ID,
STR_CALORIES_ID,
STR_STEPS_ID,
STR_DISTANCE_ID,
STR_WEIGHT_LOSS_ID,
STR_PROFORMANCE_ID,
STR_CUSTOM_ID,
STR_WIFIOK_ID,
STR_NOIP_ID,
STR_NOMAC_ID,
//#endif

STR_CALORIES_TITLE_ID,//120
STR_MILE_TITLE_ID,
STR_KM_TITLE_ID,
STR_INCLINE_TITLE_ID,
STR_MPH_TITLE_ID,
STR_SPEED_TITLE_ID,
STR_PACE_TITLE_ID,
STR_HR_TITLE_ID,
STR_METS_TITLE_ID,
STR_RESISTANCE_TITLE_ID,
STR_WATTS_TITLE_ID,
STR_RPM_TITLE_ID,//130

STR_PRESSSTART_TITLE_ID,
STR_PRESSPAUSE_TITLE_ID,

STR_0_TITLE_ID,//number0
STR_1_TITLE_ID,
STR_2_TITLE_ID,
STR_3_TITLE_ID,
STR_4_TITLE_ID,
STR_5_TITLE_ID,
STR_6_TITLE_ID,
STR_7_TITLE_ID,//140
STR_8_TITLE_ID,
STR_9_TITLE_ID,//number9


STR_SAFEKEY_OFF_ID,

STR_SETHEARTRATE_ID,
STR_HILLCLIMB_ID,
STR_CONWATTS_ID,
//STR_SPRINT8_ID,
/*
STR_Models1_ID,
STR_Models2_ID,
STR_Models3_ID,//150
STR_Models4_ID,
STR_Models5_ID,
STR_Models6_ID,
STR_Models7_ID,
STR_Models8_ID,
STR_Models9_ID,
STR_Models10_ID,
STR_Models11_ID,
STR_Models12_ID,*/

STR_RF_SYNC_ID,//160
STR_RF_SYNC_FINISH_ID,
STR_RF_SYNC_TIMEOUT_ID,
STR_ENG0_ID,
//STR_DISPLAY_TEST_ID,

/*for eng1*/
STR_ENG1_ID,

/*for eng2*/
STR_ENG2_ID,
//STR_NOT_AVAILABLE_ID,

/*for eng3*/
STR_ENG3_ID,
//STR_SWITCH_FUNCTION_ID,

/*for eng4*/
STR_ENG4_ID,
/*for eng4*/
STR_ENG5_ID,
//STR_INFORMATION_ID,

/*for eng8*/
STR_ENG8_ID,

STR_DAPI_ID,
STR_PRODUCTION_ID,
STR_QA_ID,
STR_STAGING_ID,
//STR_TEST_ID,

//STR_RPM_ID,

STR_USBTEST_ID,
STR_USBTESTING_ID,//170
STR_USBTESTPASS_ID,
STR_USBTESTFAIL_ID,
/*ENG2 P1~P6*/
STR_P1_ID,
STR_P2_ID,
STR_P3_ID,
STR_P4_ID,
STR_P5_ID,
STR_P6_ID,

STR_TREADMILL_ID,
STR_EP_ID,//180
STR_BIKE_ID,
STR_AS_ID,

STR_TF30_ID,
STR_TF50_ID,
STR_T50_ID,

//model name for EP/BK
STR_R30_ID,
STR_U30_ID,
STR_SE30_ID,

STR_R50_ID,
STR_U50_ID,//190
STR_SE50_ID,

STR_A30_ID,
STR_A50_ID,
STR_T70_ID,

STR_RETOOTING_ID,

STR_BOOT_ON_ID,
STR_BOOT_OFF_ID,
STR_TIME_ID,
STR_ACC_INFO_ID,

STR_UCB_ID,
STR_MCB_ID,//200
STR_BURN_TITLR_ID,
STR_SET_ERP_TIME_ID,
STR_SET_RPM_ID,
//STRINGIDEND
STR_WIFI_SUCCESS_ID,
STR_WIFI_FAIL_ID,
STR_WIFI_WAITTING_ID,
STR_WIFI_TIMEOUT_ID,
STR_WIFI_ACTIVATED_ID,

STR_SETUPENG_ID,
STR_KGS_ID,
STR_LBS_ID,//210
STR_KPH_TITLE_ID,
STR_RPM_ID,
STR_ADC_ID,
STR_ECB_ID,
STR_PWM_ID,


STR_TITLE_DISPLAY_ID,
STR_TITLE_ALLDOTSON_ID,
STR_TITLE_ALLDOTSOFF_ID,
STR_TITLE_SEG1_ID,
STR_TITLE_SEG2_ID,
STR_TITLE_SEG3_ID,
STR_TITLE_HARDWARETEST_ID,
STR_TITLE_BASICFUNCTION_ID,
STR_TITLE_USBPORT_ID,
STR_TITLE_WIFI_ID,
STR_TITLE_NOTAVAILABLE_ID,
STR_TITLE_SWITCHFUNCTION_ID,
STR_TITLE_STANDARDORMETRIC_ID,
STR_TITLE_LANGUAGESELECTION_ID,
STR_TITLE_MACHINESELECTION_ID,
STR_TITLE_MODELSELECTION_ID,
STR_TITLE_ENERGYMODE_ID,
STR_TITLE_FIRSTBOOT_ID,
STR_TITLE_INFORMATION_ID,
STR_TITLE_ACCUMULATEDINF_ID,
STR_TITLE_UCBVERSION_ID,
STR_TITLE_MCBVERSION_ID,
STR_TITLE_TEST_ID,
STR_TITLE_PROGRAMACCELERATOR_ID,
STR_TITLE_CLEARUSERDATA_ID,
STR_TITLE_BURNCHECK_ID,
STR_TITLE_QUICKSTANDBYMODE_ID,
STR_TITLE_RESERVED_ID,
STR_SELECT_MODEL_ID,
STR_SELECT_LANGUAGE_ID,
STR_SELECT_UNIT_ID,
STR_UNSUPPORTED_MCB_FOUND_ID,
STR_USB_UPDATE_NOTIES_ID,
STR_USB_BTUPDATE_NOTIES_ID,
STR_USB_BTUPDATEED_FAIL_ID,
STR_DEMO_ID,
STR_NULL_ID,
STR_WARMUP_ID,
STR_COOLDOWN_ID,
STR_READY_ID,
STR_RUN_ID,
STR_SPRINT1_ID,
STR_SPRINT2_ID,
STR_SPRINT3_ID,
STR_SPRINT4_ID,
STR_SPRINT5_ID,
STR_SPRINT6_ID,
STR_SPRINT7_ID,
STR_SPRINT8_ID,
STR_CUSTOM_TIME_ID,
STR_CUSTOM_DISTANCE_ID,
STR_CUSTOM_SEGMENT_ID,
STR_CUSTOMHR_ID,
STR_CUSTOM_TOTALTIME_ID,
STR_DISTANCE_MAX_ID,
STR_MYFIRST5K_ID,
STR_WALKSPEED_ID,
STR_JOGSPEED_ID,
STR_SELECTCALORIES_ID,
STR_SELECTDISTANCE_ID,
STR_MARATHON_ID=STR_SELECTDISTANCE_ID+12,
STR_HEART_RATE_ID,
STR_TIMEORDISTANCE_BASED_ID,
STR_NEXT_IN_2_DAYS_ID,
STR_NEXT_IN_3_DAYS_ID,
STR_CONGRATULATIONS_ID,
STR_MYFIRST5K_1WEEKMISSED_ID,
STR_MYFIRST5K_2WEEKMISSED_ID,
STR_HEART_RATE_MONITOR_ONLY_ID,
STR_TABLET_ENABLED_ID,
STR_KEY_TEST_ID,
STRINGIDEND
}STRINGID;

typedef enum{
  SystemConfigStringStart=  STRINGIDEND,
}SystemConfigString;

typedef enum{
	LANGUAGEIDSTART,
	_ENGLISH = LANGUAGEIDSTART,
	#ifdef __LANGUAGE_FRENCH__
	_FRENCH,
	#endif
	#ifdef __LANGUAGE_GERMAN__
	_GERMAN,
	#endif
	#ifdef __LANGUAGE_DUTCH__
	_DUTCH,
	#endif
	#ifdef __LANGUAGE_SPANISH__
	_SPANISH,
	#endif
	#ifdef __LANGUAGE_ITALIAN__
	_ITALIAN,
	#endif
	#ifdef __LANGUAGE_PORTUGUESE__
	_PORTUGUESE,
	#endif
	#ifdef __LANGUAGE_VIETNAMESE__
	_VITNAMESE,
	#endif

	LANGUAGEIDEND
}LANGUAGEID;


char* String_Get_String( STRINGID StringID );
void String_Set_Language( UCHAR languageID );
void String_Init_Data( void );

#endif
