#ifndef _STRINGS
#define _STRINGS
#include "jisdef.h"

//#define __LANGUAGE_FRENCH__
//#define __LANGUAGE_GERMAN__
//#define __LANGUAGE_DUTCH__
//#define __LANGUAGE_SPANISH__
//#define __LANGUAGE_ITALIAN__
//#define __LANGUAGE_PORTUGUESE__
//#define __LANGUAGE_VIETNAMESE__

typedef enum{
STRINGIDSTART=0,
STR_FEMALE_ID = STRINGIDSTART,
STR_GO_ID,
STR_KM_ID,
STR_STAIRS_ID,
STR_SPM_ID,
STR_HEIGHT_ID,
STR_LEVEL_ID,
STR_METRIC_ID,
STR_METS_ID,
STR_MILES_ID,
STR_RPM_ID,
STR_SPRINT1_ID,
STR_SPRINT2_ID,
STR_SPRINT3_ID,
STR_SPRINT4_ID,
STR_SPRINT5_ID,
STR_SPRINT6_ID,
STR_SPRINT7_ID,
STR_SPRINT8_ID,
STR_LANDMARK_ID,
STR_RECOVERY1_ID,
STR_RECOVERY2_ID,
STR_RECOVERY3_ID,
STR_RECOVERY4_ID,
STR_RECOVERY5_ID,
STR_RECOVERY6_ID,
STR_RECOVERY7_ID,
STR_WATTS_ID,
STR_MILE_ID,
STR_WARMUP_ID,
STR_RAMPUP_ID,
STR_READY_ID,
STR_SET_ID,
STR_HR_ID,
STR_MALE_ID,
STR_MPH_ID,
STR_KPH_ID,
STR_PACE_ID,
STR_CALORIES_ID,
STR_COOLDOWN_ID,
STR_INCLINE_ID,
STR_RESISTANCE_ID,
STR_SPEED_ID,
STR_DISTANCE_ID,
STR_ROLLINGHILLS_ID,
STR_PAUSE_ID,
STR_PLEASE_WAIT_ID,
STR_THR_ID,
STR_TIME_ID,
STR_TREADMILL_ID,
STR_ELLIPTICAL_ID,
STR_BIKE_ID,
STR_ASCENT_ID,
STR_STEPPER_ID,
STR_CLIMBMILL_ID,
STR_WELCOME_ID,
STR_WORKOUT_PAUSED_ID,
STR_XID_ID,
STR_ACTIVATED_ID,
STR_DELETE_USER_ID,
STR_ENGLISH_ID,
STR_SPANISH_ID,
STR_FRENCH_ID,
STR_ITALIAN_ID,
STR_GERMAN_ID,
STR_DUTCH_ID,
STR_PORTUGUESE_ID,
STR_VIETNAMESE_ID,
STR_CLIMB_MILL_LUBE_BELT_ID,//STRINGS NULL  NOT USE
STR_PASSPORT_READY_ID,
STR_PRESS_START_ID,
STR_PROGRAMMING_ID,//STRINGS NULL  NOT USE
STR_RF_SYNC_ID,
STR_SELECT_USER_ID,
STR_SET_AGE_ID,
STR_SET_GENDER_ID,
STR_SET_INCLINE_ID,
STR_SET_LEVEL_ID,
STR_SET_RESISTANCE_ID,
STR_SET_SPEED_ID,
STR_SET_TIME_ID,
STR_SET_TARGET_ID,
STR_SET_TARGET1,
STR_SET_TARGET2,
STR_SET_TARGET3,
STR_SET_TARGET4,
STR_SET_TARGET5,
STR_SET_TARGET6,
STR_SET_TARGET7,
STR_SET_TARGET8,
STR_SET_TARGET9,
STR_SET_TARGET10,
STR_SET_WEIGHT_ID,
STR_STANDARD_ID,
STR_UPDATE_COMPLETE_ID, //STRINGS NULL  NOT USE
STR_UPDATE_UPDATE_COMPLETED_PLEASE_PRESS_ENTER_ID,//STRINGS NULL  NOT USE
STR_UPDATE_SOFTWARE_FAILED_PLEASE_PRESS_ENTER_ID,//STRINGS NULL  NOT USE
STR_WORKOUT_COMPLETE_ID,
STR_INITIAL_ID,
STR_UPDATING_USER_INFO_ID,
STR_SET_TIMEZONE_ID,
STR_CONNECTING_WIFI_ID,                     //STRINGS NULL  NOT USE
STR_SET_TARGET_WATTS_ID,
STR_SET_THR_ID,                             //STRINGS NULL  NOT USE
STR_ERROR_NO_HEART_RATE_ID,                 //STRINGS NULL  NOT USE
STR_HEART_RATE_CONTROL_ID,                  //STRINGS NULL  NOT USE
STR_TIME_OUT_ID,
STR_ENTER_PASSCODE_ID,
STR_ENTER_XID_ID,
STR_EDIT_USER_ID,
STR_SELECT_PROGRAM_ID,                      //STRINGS NULL  NOT USE
STR_EDIT_A_USER_ID,
STR_DELETE_A_USER_ID,
STR_USER_LOGIN_ID,
STR_INVALID_USER_PIN_ID,
STR_SUCCESS_ID,
STR_WIFI_IS_OFFLINE_ID,                     //STRINGS NULL  NOT USE
STR_SAFETY_KEY_OFF_ID,
STR_HEARTRATE_ID,                           //STRINGS NULL  NOT USE
STR_SET_TARGET_HEARTRATE_ID,
STR_RF_SYNC_TIMEOUT_ID,                     //STRINGS NULL  NOT USE
STR_TF30_ID,
STR_TF50_ID,
STR_T50_ID,
STR_R30_ID,
STR_U30_ID,
STR_E30_ID,
STR_R50_ID,
STR_U50_ID,
STR_E50_ID,
STR_A30_ID,
STR_A50_ID,
STR_T70_ID,
STR_C50_ID,
STR_T30_ID,
STR_T75_ID,

STR_REBOOTING_ID,
STR_WIFI_SUCCESS_ID,                //STRINGS NULL  NOT USE
STR_WIFI_FAIL_ID,
STR_WIFI_WAITING_ID,                //STRINGS NULL  NOT USE
STR_WIFI_TIMEOUT_ID,                //STRINGS NULL  NOT USE
STR_POWER_OFF_ON_ID,                //STRINGS NULL  NOT USE
STR_DOWNLOADING_SOFTWARE_ID,        //STRINGS NULL  NOT USE
STR_DOWNLOADING_ID,
STR_UPDATE_SOFTWARE_ID,             //STRINGS NULL  NOT USE
STR_SOFTWARE_UPDATE_PRESS_ENTER_FOR_YES_BACK_FOR_NO_ID,//STRINGS NULL  NOT USE
STR_SAVE_WORKOUT_PRESS_ENTER_FOR_YESY_BACK_FOR_NO_ID,//STRINGS NULL  NOT USE
STR_PRESS_ENTER_TO_CONFIRM_ID,      //STRINGS NULL  NOT USE
STR_SOFTWARE_UPDATE_NO_SOFTWARE_ON_USB_ID,//STRINGS NULL  NOT USE
STR_SOFTWARE_UPDATE_PRESS_ENTER_ID,
STR_CONSTANT_WATTS_ID,
STR_FATBURN_ID,
STR_INTERVALS_ID,
STR_MANUAL_ID,
STR_FITNESS_TEST_ID,            //STRINGS NULL  NOT USE
STR_GUEST_ID,
STR_USER1_ID,
STR_USER2_ID,
STR_USER3_ID,
STR_USER4_ID,
STR_LUBE_BELT_ID,
STR_LBS_ID,
STR_KG_ID,
STR_IR_SENSOR_ERROR_ID,
STR_IR_CONTROLZONE_ERROR_ID,
STR_IR_UCBEMERG_ERROR_ID,
STR_IR_HANDRAILEMERG_ERROR_ID,
STR_0_TITLE_ID,
STR_1_TITLE_ID,
STR_2_TITLE_ID,
STR_3_TITLE_ID,
STR_4_TITLE_ID,
STR_5_TITLE_ID,
STR_6_TITLE_ID,
STR_7_TITLE_ID,
STR_8_TITLE_ID,
STR_9_TITLE_ID,
/*Below is used for ENG */
STR_ENG0_ID,
STR_ENG1_ID,
STR_ENG2_ID,
STR_ENG3_ID,
STR_ENG4_ID,
STR_ENG5_ID,
STR_ENG8_ID,
STR_DISPLAY_TEST_ID,
STR_HARDWARE_TEST_ID,
STR_NOT_AVAILABLE_ID,
STR_SWITCH_FUNCATION_ID,
STR_INFORMATION_ID,
STR_ENERGY_SAVE_ON_ID,
STR_ENERGY_SAVE_OFF_ID,
STR_TEST_ID,
STR_QUICK_ID,
STR_NORMAL_ID,
STR_NO_CLEAR_ID,
STR_CLEAR_ID,
STR_PRESS_START_ENTER_ERP_ID,
STR_RPM_OFF_ID,
STR_RPM_ON_ID,
STR_WIFI_TEST_ID,
STR_AUTO_ADC_ID,
STR_AUTO_INCLINE_PASS,
STR_AUTO_INCLINE_FAIL,
STR_WIFI_IS_OK_ID,
STR_NO_IP_ADDRESS_ID,
STR_NO_MAC_ADDRESS_ID,
STR_WIFI_TEST_FAIL_ID,      //STRINGS NULL  NOT USE
STR_SET_DAPI_ID,
STR_PRODUCTION_ID,
STR_QA_ID,
STR_STAGING_ID,             //STRINGS NULL  NOT USE
STR_DEV_ID,
STR_USB_TEST_ID,
STR_USB_TESTING_ID,
STR_USB_TEST_PASS_ID,       //STRINGS NULL  NOT USE
STR_USB_TEST_FAIL_ID,       //STRINGS NULL  NOT USE
STR_WIFITESTFAIL_ID,        //STRINGS NULL  NOT USE
//STR_P1_ID,
//STR_P2_ID,
//STR_P3_ID,
//STR_P4_ID,
//STR_P5_ID,
//STR_P6_ID,
//STR_P7_ID,
//STR_P8_ID,
//STR_P9_ID,
//STR_P10_ID,
STR_BOOT_ON_ID,
STR_BOOT_OFF_ID,
STR_OVERSPEED_ON_ID,
STR_OVERSPEED_OFF_ID,

STR_ERRORCODE_ON_ID,
STR_ERRORCODE_OFF_ID,
STR_CONTROL_ZONE_ON_ID,
STR_CONTROL_ZONE_OFF_ID,
STR_SECOND_CONTROL_ZONE_ON_ID,
STR_SECOND_CONTROL_ZONE_OFF_ID,
STR_1ST_CONTROL_ZONE_ID,
STR_2ND_CONTROL_ZONE_ID,
STR_REAL_CONTROL_ZONE_ID,
STR_TRAGET_CONTROL_ZONE_ID,
STR_IR_SENSOR_ON_ID,
STR_IR_SENSOR_OFF_ID,
STR_MAX_LEVEL_ID,

STR_ACC_INFO_ID,//STRINGS NULL  NOT USE
STR_SET_ERP_TIME_ID,
STR_SET_OVER_SPEED_ID,
STR_SET_RPM_ID,
STR_ADC_ID,     //STRINGS NULL  NOT USE
STR_ECB_ID,
STR_PWM_ID,     //STRINGS NULL  NOT USE
STR_ACCUMULATED_INFO_ID,
STR_UCB_VERSION_ID,
STR_MCB_VERSION_ID,
STR_RESERVED_ID,    //STRINGS NULL  NOT USE
STR_MACHINE_ID,
STR_LANGUAGE_ID,
STR_UNIT_ID,
STR_UPDATE_FROM_USB_Y_N_ID,//STRINGS NULL  NOT USE
STR_NULL_ID,
STR_ACCUMULATE_AGING_HOURS_ID,
STR_KEY_TEST_ID,
STR_SPEED_RANGE_ERROR_ID,
STR_LANGUAGE_UPDATE_PRESS_ENTER_ID,
STR_LANGUAGE_UPDATEING_ID,
STRINGIDEND
}STRINGID;
typedef enum{
    PX_STRINGIDSTART=0,
    STR_P1_ID = PX_STRINGIDSTART,
    STR_P2_ID,
    STR_P3_ID,
    STR_P4_ID,
    STR_P5_ID,
    STR_P6_ID,
    STR_P7_ID,
    STR_P8_ID,
    STR_P9_ID,
    STR_P10_ID,
    STR_RSCU_ON_ID,
    STR_RSCU_OFF_ID,
    PX_STRINGIDEND
}PX_STRINGID;

typedef enum{
  SystemConfigStringStart=  STRINGIDEND,
}SystemConfigString;

typedef enum{
	LANGUAGEIDSTART,
	_ENGLISH = LANGUAGEIDSTART,
    #ifdef __LANGUAGE_SPANISH__
	_SPANISH,
	#endif
    #ifdef __LANGUAGE_FRENCH__
	_FRENCH,
	#endif
    #ifdef __LANGUAGE_ITALIAN__
	_ITALIAN,
	#endif
	#ifdef __LANGUAGE_GERMAN__
	_GERMAN,
	#endif
	#ifdef __LANGUAGE_DUTCH__
	_DUTCH,
	#endif
	#ifdef __LANGUAGE_PORTUGUESE__
	_PORTUGUESE,
	#endif
	#ifdef __LANGUAGE_VIETNAMESE__
	_VITNAMESE,
	#endif

	LANGUAGEIDEND
}LANGUAGEID;


char* String_Get_String( STRINGID StringID );
char* PxString_Get_PxString( PX_STRINGID StringID );
void String_Set_Language( UCHAR languageID );
void String_Init_Data( void );
UCHAR String_Get_LanguageIndex(void);
#endif
